### ISSUE TITLE
Documentation for Strain Description

### ISSUE THREAD

**Issue by brynhayder** [SBRG/precise2#3]
Thank you for making your work public.

Is it possible to add documentation that provides a key/dictionary for how we should understand the strain description? For instance, how should I interpret something like `Escherichia Coli ERS.1.112`?

**Comment by avsastry** [comment]
Hi Bryn, many of these strain names are aligned with strains in our Adaptive Laboratory Evolution (ALE) strain collection hosted at https://aledb.org/. Figure 5 in [the accompanying paper](https://academic.oup.com/nar/article/47/D1/D1164/5144149) explains our nomenclature, where the letters are related to the project, the first number is the index of the ALE experiment, the second number is the name of the flask, and the third is the isolate. Some of the mutation information for these strains will remain private until the associated manuscript is published. Please let me know if you have additional questions!
