### ISSUE TITLE
Provided data files and normalization efforts

### ISSUE THREAD

**Issue by erbsl** [SBRG/precise2#6]
Hi everyone

Thanks for providing your extensive database for others to play around with :)
I was wondering about the provided tpm files for precise 2.0: What norm step took place for tpm_log_norm_qc? Is all provided data (tpm_log, tpm_log_qc and tpm_log_norm_qc) been processed as described in https://doi.org/10.1093/nar/gkaa810 (including DESeq2 normalization) or have procedures and QC been altered?

Thanks in advance

**Comment by avsastry** [comment]
All the data has been processed as reported in this paper (which should be identical to the paper you linked):

The pipeline used itself is from here:
https://github.com/avsastry/modulome-workflow

log-TPM means log2-transformed transcripts per million
log_tpm_qc is the output of the QC protocol: https://github.com/avsastry/modulome-workflow/tree/main/3_quality_control
log_tpm_qc_norm is the above dataset, but centered to a reference condition.

**Comment by avsastry** [comment]
Actually quick note, we used featureCounts here, instead of DESeq2. See the pipeline linked above
